### ISSUE TITLE
Tracking: TestFlight tasks

### ISSUE THREAD

**Issue by m-005** [xmtp-labs/xmtp-inbox-ios#32]
```[tasklist]
### Tasks
- [ ] https://github.com/xmtp-labs/xmtp-inbox-ios/pull/31
- [ ] https://github.com/xmtp-labs/xmtp-inbox-ios/issues/33
- [x] Create iOS App Icon
```

**Comment by m-005** [comment]
@nakajima Once we have the High and Med priority tracking issues closed out, we should be good to push this forward to an external TestFlight. It'd also be helpful to have an external to get the last few people on the team onboarded as part of our OKR initiative. See any blockers for just the external TestFlight review?
